"""Add id field to wholesale company detail

Revision ID: 217103290d51
Revises: 
Create Date: 2025-06-20 23:36:18.835098

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217103290d51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 먼저 id 컬럼을 nullable로 추가
    op.add_column('wholesale_company_details', sa.Column('id', sa.UUID(), nullable=True))
    
    # 기존 데이터에 UUID 생성
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE wholesale_company_details 
        SET id = gen_random_uuid() 
        WHERE id IS NULL
    """))
    
    # id 컬럼을 NOT NULL로 변경
    op.alter_column('wholesale_company_details', 'id', nullable=False)
    
    # company_id에 unique constraint 추가
    op.create_unique_constraint(None, 'wholesale_company_details', ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wholesale_company_details', type_='unique')
    op.drop_column('wholesale_company_details', 'id')
    # ### end Alembic commands ###
